import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import './styles.css';

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HydraLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className={montserrat.className} style={{zIndex: -99, position: "relative"}}>{children}</div>;
}
