import type { Metadata } from "next";
import localFont from "next/font/local";
import { Rubik } from "next/font/google";
import "./styles.css";

const satoshi = localFont({
  src: [
    { path: "../../fonts/Satoshi/Satoshi-Regular.otf", weight: "400" },
    { path: "../../fonts/Satoshi/Satoshi-Medium.otf", weight: "500" },
    { path: "../../fonts/Satoshi/Satoshi-Bold.otf", weight: "700" },
    { path: "../../fonts/Satoshi/Satoshi-Black.otf", weight: "900" },
  ],
  display: "swap",
  variable: "--font-satoshi",
});

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function FinanceLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${rubik.className} ${satoshi.variable}`} style={{zIndex: -99, position: "relative"}}>{children}</div>
  );
}
