import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import './styles.css';

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AnalyticsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className={roboto.className}>{children}</div>;
}
